### ISSUE TITLE
wasmparser reporting illegal opcode

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [bytecodealliance/wasm-tools#1067]
I have a recently compiled (rustc/cargo) wasm file, that when parsing it using wasmparser crate ("0.107.0" from crates.io) reports:

```
illegal opcode: 0xa (at offset 0xd8)
```

I think I saw this error previously in one of the non-maintained C++ wasm optimization tools, and when I searched it turned out it was a newer opcode that was not in the original spec and the tool hadn't been updated to support it.

`wasm-objdump` and other tools can process it without problems.

But, I expected wasmparser to be up to date.

Am I misunderstanding something?
Do I need a feature or flag or some other change in order to process such a file correctly?

(I could attach the file but its > 100K) and not sure that would be appreciated.

**Comment by alexcrichton** [comment]
Thanks for the report! If you could upload the wasm file that'd be appreciated, or gist the `wasm-tools dump foo.wasm` report would probably work too

**Comment by andrewdavidmackenzie** [comment]
[compare_switch_wasm.txt](https://github.com/bytecodealliance/wasm-tools/files/11754166/compare_switch_wasm.txt)

GH doesn't accept .wasm files, so I renamed to .txt and uploaded.

here is the cargo projection  I use to compile this (nothing of interest IMO):
```
[package]
name = "compare_switch"
version.workspace = true
authors.workspace = true
edition.workspace = true (is 2021)

[lib]
name = "compare_switch"
crate-type = ["cdylib"]
path = "compare_switch.rs"

[dependencies]
flowcore = { workspace = true }
flowmacro = { workspace = true }
serde_json = { workspace = true, default-features = false }
```

I think it was compiled with: 
`cargo 1.72.0-nightly (f7b95e316 2023-05-30)` and
`rustc 1.72.0-nightly (d59363ad0 2023-06-01)`

**Comment by alexcrichton** [comment]
Hm can you share the code that's processing this wasm file? The wasm file passes `wasm-tools validate` locally for me which means wasmparser is parsing and validating the file correctly. This file looks normal like it shouldn't require any extra flags or anything like that.

One odd thing is that the offset in your error message, `0xd8`, is an offset into the function section which shouldn't produce the error `illegal opcode` since that only comes about from reading the code section. That may mean that the code using `wasmparser` may have a bug in it.

**Comment by alexcrichton** [comment]
Ah yes that's not how a wasm file is parsed, the `BinaryReader` gives really low-level access so what's happening here is you're interpreting the entire wasm file as a list of bytecode, which isn't correct since it has much more structure than that. You'll want to start at the top-level with a `wasmparser::Parser`

**Comment by andrewdavidmackenzie** [comment]
Aha. So I guess you need to parse down and find function bodies and then use the BinaryReader on that, and not the whole module.

If you know of any good readable code or examples or parsing modules, that would be much appreciated - I will continue to try anyway.

Thanks.

I'll close the issue.
