### ISSUE TITLE
Unification of `wasmparser` and `wasm_encoder` types

### ISSUE THREAD

**Issue by arnaudgolfouse** [bytecodealliance/wasm-tools#1115]
I am using `wasmparser` to parse a wasm binary, and then `wasm_encoder` to rebuild it with some changes (to be precise, I am replacing each "wasi_snapshot_preview1" import with a dummy function).

Doing this I noticed that a lot of types are repeated almost verbatim between `wasmparser` and `wasm_encoder`, leading to a lot of annoying conversions. Looking at the various crates in `wasm-tools`, it seems that they also deal with those conversions a lot.

I think at least some of those types may be unified, and originate from a single crate. I did a very early test of that at <https://github.com/arnaudgolfouse/wasm-tools/tree/wasm-types>, and it looked quite promising. Is there some isues with this approach ?

**Comment by alexcrichton** [comment]
I definitely agree that there's quite a lot of overlap between the declarations of `wasmparser` and `wasm-encoder`, and on the surface I agree they should ideally be the exact same hierarchy. I've found this difficult in the past to execute on, however, due to a few reasons:

* There's subtly different representations for some opcodes, such as `BrTable`
* There exist consumers of only `wasmparser` and consumers of only `wasm-encoder`, and having the exact same types often comes at the cost of one of those consumers. (e.g. if everything used `Vec` for `BrTable`)
* People who work on `wasm-encoder` or `wasmparser` may not want to immediately have to work on the other. For example new opcodes could be added to `wasmparser` before `wasm-encoder` for testing but having one type hierarchy forces everything to be done at once. To me this is a cost to eat, however, but one to still recognize.
* Idioms change over time and keeping crates tied at the hip introduces maintenance burden. For example the fastest way to parse opcodes in `wasmparser` is with trait methods rather than the enum-based approach that `wasm-encoder` takes. Refactoring one to the other isn't always easy. Like the before point though I think this is a cost to eat, but again still one to recognize.

I suppose I'm talking about opcodes here, but to me types are even trickier than opcodes. Especially in the face of the component model and GC where types get recursive the representation choice is significant. I do find it nice to decide each in a silo today, but I also don't want to diminish the fact that read, modify, encode use cases are "left out in the dry".

If you're curious [this file](https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wit-component/src/gc.rs) is an implementation of a read-modify-write pass on a wasm module which may help serve as an inspiration for a similar tool. I don't think existence of that is by any means grounds to close this issue, however, since that module would likely be a lot nicer with shared type hierarchies.

**Comment by fitzgen** [comment]
Yeah I wouldn't want to have these crates use the same types so much as consolidate our type conversion in a single place.

I think adding a `from-wasmparser` feature to `wasm-encoder` that unlocks `impl TryFrom<wasmparser::Foo> for wasm_encoder::Foo` might be the best approach. (`TryFrom` because the types don't always line up and support for features doesn't always line up either).
