### ISSUE TITLE
Adaptor Failing to Decode Custom Section

### ISSUE THREAD

**Issue by jordan-rash** [bytecodealliance/wasm-tools#1155]
My recent journeys into the webassemby universe have run into the following issue.  The most recent tagged adaptors are bubbling up the below error when creating a component.  The issue seems to have been fixed in dev...

Environment:
```
└─❯ tinygo version  
tinygo version 0.28.1 darwin/arm64 (using go version go1.20.6 and LLVM version 15.0.7)

└─❯ wasm-tools --version
wasm-tools 1.0.38 (64fee0e54 2023-07-26)

└─❯ wit-bindgen --version
wit-bindgen-cli 0.9.0 (bf318b8ae 2023-07-27)
```

Here is creating the component with reactors from dev and the latest tagged version (see file name used in command)
```
└─❯ wasm-tools component new main.embed.wasm --adapt wasi_snapshot_preview1=./wasi_snapshot_preview1.reactor.dev.wasm -o main.component.wasm


└─❯ wasm-tools component new main.embed.wasm --adapt wasi_snapshot_preview1=./wasi_snapshot_preview1.reactor.v11.0.1.wasm -o main.component.wasm
error: decoding custom section component-type:reactor

Caused by:
    0: record type must have at least one field (at offset 0xd)
```

Text of error [location](https://github.com/bytecodealliance/wasm-tools/blob/64fee0e54eed6fe3bf07a43e4f559621d0cb3eac/crates/wit-component/src/metadata.rs#L127)

-------------------------

Steps to recreate:
```
└─❯ tinygo build -target=wasi -scheduler=none -o main.wasm gopher.go

└─❯ wasm-tools component embed --world critter . main.wasm -o main.embed.wasm

└─❯ wasm-tools component new main.embed.wasm --adapt wasi_snapshot_preview1=./wasi_snapshot_preview1.reactor.wasm -o main.component.wasm
```

**Comment by peterhuene** [comment]
The component model proposal was updated such that new validation rules were put in place to prevent records with no fields (as well as other empty types). The reasoning behind this is that not all languages can represent empty records in a consistent way with the ABI.

Unfortunately, this means that older WASI adapters no longer validate with the most recent `wasm-tools` due to a (temporarily) empty record type that was used to denote errors.

Thus, the latest `wasm-tools` will require using commit `7b9189b` (or more recent) out of the `main` branch for the WASI adapters.

**Comment by jordan-rash** [comment]
Thanks so much for the information @peterhuene!!!!
