### ISSUE TITLE
Remove component `union` types

### ISSUE THREAD

**Issue by lann** [bytecodealliance/wasm-tools#1179]
See: https://github.com/WebAssembly/component-model/issues/236

**Comment by lann** [comment]
@alexcrichton Assuming this goes through, any thoughts on rolling it out? It doesn't seem like anyone is (publicly) using them so I would lean toward just removing across codebases all at once, but you could obviously argue for a deprecation phase too.

**Comment by alexcrichton** [comment]
I was actually just talking about this with Till the other day, and our rough conclusion was that so long as no one's using a feature it's safe to remove (a bit of a tautology when written out but hey). In that sense because WASI does not use `union` types I think it's ok to remove it whenever. It'll take time to percolate throughout the tools but that should be ok given the rare usage of it.
