### ISSUE TITLE
wit-parser: distinguish between imported and exported resources

### ISSUE THREAD

**Issue by dicej** [bytecodealliance/wasm-tools#1197]
While implementing resource support for the `wit-bindgen` Rust and C generators, and now again in `componentize-py`, I've realized that the hardest part is keeping track of whether a resource is being exported or imported.  This isn't a problem when a resource is _only_ being imported or _only_ being exported, but it becomes a problem when it's both imported and exported because the code we generate depends on whether or not the resource is implemented locally,

Currently, `wit-parser` doesn't explicitly indicate whether or not a resource is local, so it's up to the binding generator to keep track of it based on the context.  Rather than duplicate that effort across all the generators, I'd like to propose that we modify `wit-parser` to generate two separate `TypeId`s for a resource that's both imported and exported, plus add a payload to `TypeDefKind::Resource` indicating which direction it represents.

**Comment by alexcrichton** [comment]
I think this makes sense and I like the idea behind it, consolidating functionality in `wit-parser` where possible, but at the same time I think this'll be difficult to do given the data structures and AST of `wit-parser`. Currently the reason that this is a problem is that if you have:

```wit
interface foo {
  resource a
}

world bar {
  import foo
  export foo
}
```

the `import` and `export` statements of the `bar` world both have the exact same `InterfaceId`. Splitting that into two distinct `InterfaceId`s isn't quite right because then it doesn't reflect the structure of the original document where the import/export refer to the same interface. Otherwise the question of "is this an exported resource" is also not really one that can be answered at the level of `Resolve` today.

One possible alternative solution, however, would be to have a helper data structure in `wit-bindgen-core` perhaps? That's already got helper traits for assisting the walk over the `Resolve` AST and that could be enhanced with more side tables and such to track this. In general `wit-bindgen-core` is very thin in its support and I think it'd be good to have more built-in for something like this.

I don't know exactly what a `wit-bindgen-core` thing would look like here, but it feels, at least to me, more tractable than modifying `Resolve`. I might be missing something, however, in that regard.

**Comment by dicej** [comment]
Yeah, good point about having to duplicate `InterfaceId`s.  Currently, `componentize-py` doesn't use any part of `wit-bindgen`, and the code is structured pretty differently since it needs to generate both Python and core Wasm code.  I'll see what I can come up with there and then think about how it could be factored out into a reusable utility.

**Comment by dicej** [comment]
I spoke with Alex about this further out-of-band, and we agreed this is out of scope for wit-parser.  I'll think some more about where it belongs and what it should look like.
