### ISSUE TITLE
wasm-tools smith generates infinite loops

### ISSUE THREAD

**Issue by yamt** [bytecodealliance/wasm-tools#1410]
i'm using the following to generate a wasm module.
```
    dd if=/dev/urandom bs=10240 count=100 2> /dev/null | wasm-tools smith \
    --max-imports=0 \
    --ensure-termination \
    --fuel=100 \
    --maybe-invalid \
    --reference-types-enabled=true \
    --simd-enabled=true \
    -o test.wasm
```
my expectation was that with `--ensure-termination`, it doesn't generate infinite loops.
however, it sometimes does.
i will attach a sample of a generated file, which loops infinitely.

[test.zip](https://github.com/bytecodealliance/wasm-tools/files/14229072/test.zip)

it's with `wasm-tools 1.0.55`.

**Comment by fitzgen** [comment]
Can you attach the input bytes that were given to wasm-smith such that it created a Wasm module that has infinite loops? Thanks!

**Comment by alexcrichton** [comment]
Oh I believe this is the combination of `--ensure-termination` and `--maybe-invalid` as you can [see in the `smith` subcommand](https://github.com/bytecodealliance/wasm-tools/blob/f43b4188246603088c46af7befb9f97e817ecf02/src/bin/wasm-tools/smith.rs#L101-L130). With `--maybe-invalid` the `--ensure-termination` option doesn't work because it only works if wasm-smith is generating all the bytecode itself.

Definitely something we should improve by erroring out if both options are passed.

**Comment by alexcrichton** [comment]
I've changed how things are organized in https://github.com/bytecodealliance/wasm-tools/pull/1411 and an example error looks like:

```
$ head -c 1000 /dev/urandom | tee input.bin | cargo run smith --allow-invalid-funcs true -t --ensure-termination
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/wasm-tools smith --allow-invalid-funcs true -t --ensure-termination`
error: failed to ensure module always terminates, `--ensure-termination` is incompatible with `--allow-invalid-funcs`

Caused by:
    0: failed to ensure that a function generated due to it containing arbitrary instructions
```

with [input.bin.gz](https://github.com/bytecodealliance/wasm-tools/files/14230011/input.bin.gz) as the input
