### ISSUE TITLE
Generate codes that are successfully executed

### ISSUE THREAD

**Issue by khagankhan** [bytecodealliance/wasm-tools#1457]
I want to generate the codes that are successfully executed on the target. I see that most of the rejected cases are because of imports. So I am running it like :

`wasm-tools smith --max-imports 0`

I want to know if it affects other language features to be generated by `wasm-smith`?

Best,

**Comment by alexcrichton** [comment]
Nah that should be sufficient! You might also be interested in `--available-imports` which is a way to specify import signatures if there are some imports on your platform. Either that or `--exports` can generate a module with exactly the exports specified.

Otherwise though, no, if you don't allow imports that still enables everything else to get generated.

**Comment by khagankhan** [comment]
Thank you very much for the prompt answer!

**Comment by alexcrichton** [comment]
Sure thing! I'm going to close this since I think it's been answered, but feel free to continue to post here if there's anything else.
