### ISSUE TITLE
Is wast parser encoder always removing parsed custom sections?

### ISSUE THREAD

**Issue by N0il** [bytecodealliance/wasm-tools#1488]
I created a custom section like this,`(@custom "my_custom_section")`

Then run this:
```
  if let ModuleKind::Text(fields) = &module.kind {
      for field in fields.iter() {
           if let ModuleField::Custom(cus) = field {
              println!("here")
           }
       }
   }
```

This printed here, but after encoding it into _wasm_, using encoder, and then converting it back to _wat_ the custom section disappeared.

For what I have seen the wasm2wat seems to ignore custom sections, is it because of this why I don't see the custom section?

**Comment by alexcrichton** [comment]
Are you writing code that uses the `wast` crate directly? Or are you using the `wasm-tools` CLI? In both cases could you share some more specifics about what you're doing?

I ask because this is what I see locally:

```
$ wasm-tools print <<< "(module (@custom \"foo\"))"
(module
  (@custom "foo" (before first) "")
)
```

Which shows that the custom section is parsed and then printed and is preserved through the roundtrip. Note that `wasmprinter` only started printing custom sections recently, so if you haven't already you may need to update `wasm-tools`. Also note that none of what I'm saying here is applicable if you're using the `wast` and `wasmprinter` crates, which is why I'm also asking for more details.
