### ISSUE TITLE
wasm-tools validate do not give file location

### ISSUE THREAD

**Issue by peter-jerry-ye** [bytecodealliance/wasm-tools#1608]
Hello,

I'm trying to validate a wat file with `wasm-tools validate a.wat`, and I'm getting an error message like this:
```
error: func 49 failed to validate

Caused by:
    0: type mismatch: expected f64, found i32 (at offset 0xb07)
```

I know I can figure out the error position by running `wasm-tools parse a.wat | wasm-tools print -p`, but is it possible that `wasm-tools validate` provide the file location directly? For example, `wat2wasm` would give me `a.wat:592:3: error xxx`

**Comment by alexcrichton** [comment]
Thanks for the report! This is due to how the text format is supported architecturally throughout subcommands which is that it's immediately converted to binary and then it's as-if only the binary  was provided. Supporting mapping binary locations back to the original `*.wat` file would require source maps of some kind which aren't supported by the `wast` crate right now. It's thoeretically possible to do so but might be a chunk of work.

**Comment by alexcrichton** [comment]
I'll note now that with https://github.com/bytecodealliance/wasm-tools/pull/1632 this should be somewhat possible with the `-g` flag.

**Comment by peter-jerry-ye** [comment]
@alexcrichton Thank you for your great work. Now I have the address with the `wasm-tools validate -g`.

Just one more question, is it also possible with `wasm-tools component new`? Because I'm getting

> error: failed to encode a component from module
> 
> Caused by:  
>     0: failed to validate component output  
>     1: type mismatch: expected i32 but nothing on stack (at offset 0xcbc)

and it doesn't have any intermediate output to let me see where the type mismatch occured.

**Comment by peter-jerry-ye** [comment]
OK, it seems that it was the `wasm` that was invalid.

**Comment by alexcrichton** [comment]
For that I'd recommend passing `--skip-validate` to `wasm-tools component new` and then running `validate -g` on the output binary to figure out the exact location
