### ISSUE TITLE
Maybe bring back the deprecated "try-catch-catch_all" opcodes in wasmparser::validator after the "rust-feature" flag?

### ISSUE THREAD

**Issue by trzeciak** [bytecodealliance/wasm-tools#1653]
I would like to use exceptions in wasm code in the wild. But I'm afraid that the new approach `exnref` is not yet well supported by my clients side, so I would like to use legacy exception proposal (for a while).

I also want to use sentry as crash-tracker, but I have a problem with my wasm file on sentry backend (https://github.com/getsentry/symbolic/issues/850), because getsentry/symbolic project use wasmparser::validator, but latest wasmparser are already deprecated those opcodes (https://github.com/bytecodealliance/wasm-tools/pull/1333).

I was wondering if it would be possible to handle this on the symbolic side, but now it occurred to me that maybe it could be brought back in this project and hidden behind a rust-flag?

As a test, I restored this code and confirm that it solve this problem: https://github.com/trzeciak/wasm-tools/commit/871dbcba98ad05dc3ec55d1ed91a948a2b0f9c35

**The question:**

If I prepared a PR with restoring this code in the validator, behind a flag (say `"legacy-exception-handling"`), would this be acceptable?

**Comment by alexcrichton** [comment]
Thanks for the report! I think it would be reasonable to bring back these opcodes as well if you're interested in it. Your commit looks good to me, and some comment I might have would be:

* The old opcodes should be moved under a new `WasmFeatures` like you mention which would be likely permanently off-by-default
* Could you add back some of the tests to ensure that the validator works?

One caveat is that I'd like to personally keep the s-expression-forms removed since they were somewhat cumbersome to maintain. Is that ok with you? It means that the text-to-binary transform wouldn't support `(try (do ..))` for example, you'd have to use `try ... catch_all ... end` (or something like that I forget the exact opcodes, basically you couldn't use parens in the text format)

**Comment by trzeciak** [comment]
Hi, I agree with the comments, I will include them in the PR draft.  

I'm not sure I understand the second part of your statement xD (I think):
* I don't need conversion from wasm-binary-format to textual-representation, or even from textual to binary. My code with business logic is in C++, I use emscripten to compile, it uses llvm and wasm-binary-format is created.
* I pass the wasm-binary file (with debug symbols) to sentry. If I'm not mistaken, the [getsentry/symbolic](https://github.com/getsentry/symbolic) code doesn't use binary to textual conversion either (I checked briefly, but I don't see a logical reason to do this).

Please confirm whether I understand correctly, if so, I will be able to start preparing the PR.

**Comment by trzeciak** [comment]
@alexcrichton Once again, thank you very much for accepting this idea and for your help!

**Comment by alexcrichton** [comment]
And thank you for your work here!
