### ISSUE TITLE
Invertible wasm smith

### ISSUE THREAD

**Issue by matklad** [bytecodealliance/wasm-tools#393]
That's just completely crazy, *but* the idea behind wasm smith is that we define a surjective mapping, `ws :: Vec<u8> -> WASM`, so that we can re-use coverage guided fuzzing tools. Now, if we manage to defne `sw :: WASM -> Vec<u8>` such that `ws(sw(X)) == X` (right inverse?), then we'll get minimization for free. You can start with large wasm couter-example, hydrate it to unstructured bytes, and feed the bytes as the input to the fuzzer. Not sure if that'll be more efficient/simpler to write than the direct `WASM -> WASM` shrinker, but it at least sounds cool.

**Comment by alexcrichton** [comment]
This sounds neat, but I don't think that this is something we're going to want to implement and maintain. AFAIK the `wasm-mutate` tool is going to serve the basis for shrinking wasm, and otherwise trying to maintain a parallel path of converting a wasm module back to the original bytes that it could be generated with using `wasm-smith` I think would be way too complicated to maintain for now. Currently nothing in `wasm-smith` is really architected for that and doing so would probably result in a pretty large rewrite to almost a new crate anyway.
