### ISSUE TITLE
wasm-mutate: replace instructions with constant values

### ISSUE THREAD

**Issue by nagisa** [bytecodealliance/wasm-tools#467]
This is an idea/suggestion for wasm-mutate. I'm not sure if I'll get an opportunity to implement something like this myself, but I definitely derived some value from applying a similar technique manually in the past.

As far as I know wasm-mutate will not attempt to simplify operations with dependencies on other items to simpler operations that are dependency free. This sort of transformation can enable removal of some of the definitions that aren't relevant to the test case more readily.

More generally such a transformation can be applied to an arbitrary WASM operation. The mutator would replace an operation with `N` operands and `M` results with `N` `drop` and `M` `*.const rng` operations.

For some operations that take as operands and produce as result values of the same type, fewer operations could be used to maintain the operand stack in the correct shape. e.g. `i32.add` could be replaced with a plain `drop`. I'm not entirely sure if that'd produce better or worse results. Either way it would seem that e.g. an obvious conversion to `(drop) (drop) (i32.const 42)` could be reduced to `(drop)` as a separate pass too.

**Comment by fitzgen** [comment]
We have a bunch of such rules already defined here:

https://github.com/bytecodealliance/wasm-tools/blob/5380b16c523ac3b56235d3254522504c2efedd3b/crates/wasm-mutate/src/mutators/peephole/rules.rs#L405-L538

I think we can close this issue?

**Comment by nagisa** [comment]
Aha, okay, so there is something that prevents these from triggering in at least in some of the cases I had encountered.

An example I have on hand today is `(elem (global.get 0) func)` which I suspect may be related to the fact that we only have a rule for i32 and i64 today. In the past when I did a similar transformation by hand, I think it involved floating point types. I'll look into adding rules for funcrefs, floats and others and see if reduction capabilities improve.

**Comment by nagisa** [comment]
I submitted 2 PRs that improve on what I'm suggesting here: https://github.com/bytecodealliance/wasm-tools/pull/469 https://github.com/bytecodealliance/wasm-tools/pull/470 but I don't believe these + the preexisting peephole rules are actually fully implementing what I'm suggesting.

In particular AFAICT transformation such as `(i32.add) => (drop drop i32.const.rand)`, `(local.set 10) => (drop)`, `(call ... (...)) => ((params * drop) (result * T.const.rand))` etc. are not currently implemented. While we could start adding peephole “instcombines” that do this, that would result in a huge number of rules!

Another problem I've encountered as I was working on #469 and #470 is that currently “reduction” is required to produce a strictly smaller WASM encoding. In this case most such transformations would fail to decrease (and in many cases increase) the encoded size of WASM, even if ultimately they are objectively less _complex_ and introduce opportunities for a further reduction.

**Comment by fitzgen** [comment]
> In particular AFAICT transformation such as `(i32.add) => (drop drop i32.const.rand)`, `(local.set 10) => (drop)`, `(call ... (...)) => ((params * drop) (result * T.const.rand))` etc. are not currently implemented. While we could start adding peephole “instcombines” that do this, that would result in a huge number of rules!

The rules I linked to before will do the first replacement. They match and replace whole expression subtrees, not just single instructions.

I don't believe we have any rules for `call` but it shouldn't be too hard to add support for.

> Another problem I've encountered as I was working on #469 and #470 is that currently “reduction” is required to produce a strictly smaller WASM encoding. In this case most such transformations would fail to decrease (and in many cases increase) the encoded size of WASM, even if ultimately they are objectively less _complex_ and introduce opportunities for a further reduction.

This is a known weakness of `wasm-shrink`'s reduction approach, but is deemed an acceptable trade off regardless.

The problem is that more accurate/powerful metrics of Wasm module complexity are both more complicated to define and implement and also are more expensive to compute. (E.g. a test case reducer for a source language might want to count tokens rather than byte size, to avoid considering replacing descriptive variable names with single letter names a valid reduction, but that requires O(n) tokenizing every test case rather than an O(1) read of its length.

That said, we _could_ loosen the invariants a little bit here to allow reductions that produce an identical byte size, but then we would

* have to be careful to only go "one way" with e.g. replacing global-relative data segment offsets with constant offsets
* add a `debug_assert!` to `wasm-shrink` that asserts that if we do "reduce" to the same size, then the contents of the test cases are different.

**Comment by nagisa** [comment]
I think we can close this now with https://github.com/bytecodealliance/wasm-tools/pull/523 and https://github.com/bytecodealliance/wasm-tools/pull/470 and some other PRs being merged.
