### ISSUE TITLE
Writing a JIT-like codegen tool with this library

### ISSUE THREAD

**Issue by AlexApps99** [bytecodealliance/wasm-tools#512]
Hello, I'm looking for methods to write a bytecode compiler for WASM from WASM, and I couldn't find any existing tooling to do such.

My current idea is to write a procedural macro like [`dynasm-rs`](https://github.com/CensoredUsername/dynasm-rs), but writing a custom WAT parser and assembler would be too much of an undertaking for myself.

The `wast` library seems promising, since it can do custom parsing, but it doesn't seem to have any way to handle the runtime generic values that would be needed for such a tool. I imagine it would involve reimplementing the `Parse` trait of `Instruction`, or perhaps making a new type that is a modified version of `Instruction`.

The `binary` module is private, so converting anything less than a module to bytes at build-time is not possible yet, and even if it were public, finding the byte offsets/widths of generic values so they can be filled in at runtime would be complicated.

Are there any clever solutions to this problem I haven't come across? It seems that it would be a lot of work whether I use `wast` or not.

**Comment by alexcrichton** [comment]
The `wast` and `wat` crates are primarily intended to translate from the text format of wasm to the binary format for wasm. While the `wast` crate provides a number of utilities to work with s-expressions generally it's primarily intended for wasm. It sounds like if you don't want to purely parse wasm but have a lot of custom syntax as well then this may not be the library for you since it doesn't easily support things like plugins to the parser.

**Comment by AlexApps99** [comment]
I understand, I suppose I'll have to roll my own.
Thanks
