### ISSUE TITLE
multi-memory vs bulk-memory and wasm-smith/encoder vs wasmparser

### ISSUE THREAD

**Issue by nagisa** [bytecodealliance/wasm-tools#540]
I have a Wasm which was produced by `wasm-smith` configured with `-all,multi-memory,mutable-global` features:

```
...
0x0060 | 05 0b       | memory section
0x0062 | 02          | 2 count
0x0063 | 01 87 01 fa | [memory 0] MemoryType { memory64: false, shared: false, initial: 135, maximum: Some(6394) }
       | 31         
0x0068 | 01 70 e0 ab | [memory 1] MemoryType { memory64: false, shared: false, initial: 112, maximum: Some(38368) }
       | 02         
0x006d | 0b 11       | data section
0x006f | 02          | 2 count
0x0070 | 00          | data memory[0]
0x0071 | 41 e8 9a 2b | I32Const { value: 707944 }
0x0075 | 0b          | End
0x0076 |-------------| ... 2 bytes of data
0x0079 | 02 01       | data memory[1]
0x007b | 41 ca 0f    | I32Const { value: 1994 }
0x007e | 0b          | End
0x007f |-------------| ... 0 bytes of data
```

This then promptly fails to validate with an error:

```
Error: unknown memory 2: memory index out of bounds (at offset 121)
```

This validation succeeds, if the `bulk-memory` proposal is enabled in addition to the others.

From my investigation so far, the `0x02` in question is produced by https://github.com/bytecodealliance/wasm-tools/blob/d80c87b2f313dc5309ce36e9d1a87bbe08a222e7/crates/wasm-encoder/src/core/data.rs#L104, and then wasmparser will read the `0x02` as `flags` https://github.com/bytecodealliance/wasm-tools/blob/d80c87b2f313dc5309ce36e9d1a87bbe08a222e7/crates/wasmparser/src/readers/core/data.rs#L115-L129 before returning it as the `memory_index` because the bulk-memory proposal is disabled.

On one hand, the `bulk-memory` proposal has been merged to the specification draft and `multi-memory` hasn't been. `bulk-memory` is the proposal which introduced the wording around special handling of the `0x02` flag value, causing a conflict with the `multi-memory` proposal. Given that `bulk-memory` precedes `multi-memory` it doesn't seem particularly wrong for `wasm-encoder` to assume that any occurrence of multiple memories will imply both the `bulk-memory` and `multi-memory` proposals and therefore use the `0x02 <index>` encoding as specified in the `bulk-memory` proposal.

On another hand, `wasm-encoder` could use the older `<index>` encoding if it provided any way at all to specify a weird proposal combination (`-bulk-memory,multi-memory`.)

`wasm-smith` produces multiple memories and multiple data segment entries which AFAIU both `multi-memory` and `bulk-memory` proposals allow individually, so I don't think the problem is there.

`wasm-parser` seems to be doing the right thing with any proposal combination AFAICT.

I'd love some ideas on what the best fix would be here, since it is blocking my work on https://github.com/bytecodealliance/wasm-tools/pull/539

**Comment by alexcrichton** [comment]
This is actually something where I would love to remove this support in wasmparser and personally I don't see the value in supporting this indefinitely. In my opinion an engine that implements multi-memory but doesn't implement bulk-memory is "doing the wrong thing" since there will never be a world where a "stable" wasm specification will have multi-memory and not the bulk-memory encoding.

The only reason wasmparser supports this is that there were some spec tests which we passed before the bulk-memory support was merged to the specification. These tests were very particular about the error message and how the result was interpreted. In general bulk-memory was actually a breaking change to the specification because previously accepted encodings are no longer valid (e.g. specifying `\80\00` for index 0 used to work, now it doesn't).

Personally I don't see much value in chasing standards like. I don't believe that the wasm specs are written in such a way where you can pick various proposals a-la-carte and get a working engine as a result.

**Comment by nagisa** [comment]
Right, that makes sense to me. I'll see about implementing the change.
