### ISSUE TITLE
components: Parsing type exports doesn't work

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasm-tools#674]
This component currently doesn't parse:

```wasm
(component
  (type (instance
    (type string)
    (export "" (type 0))
  ))
)
```

with:

```
Error: expected `(`
     --> foo.wat:4:22
      |
    4 |     (export "" (type 0))
      |                      ^
```

One issue is the [extra parentheses parsed here](https://github.com/bytecodealliance/wasm-tools/blob/8e94096515e80cfd71219d27ecf8a01b18228919/crates/wast/src/component/import.rs#L62-L66) which don't need to be parsed. Another though is the parsing of the [`eq` keyword](https://github.com/bytecodealliance/wasm-tools/blob/8e94096515e80cfd71219d27ecf8a01b18228919/crates/wast/src/component/import.rs#L105-L106) which I think was intended for imports.

I'm not sure what the current state of things are though. Type imports aren't actually valid according to the validator at the moment so I'm not sure if the `eq` there can be removed.

Similarly though if type imports aren't allowed it seems like type exports aren't allowed. Overall it seems like there needs to be work done at the spec level to rationalize/clarify all this first.

cc @peterhuene

**Comment by alexcrichton** [comment]
Ah ok, if that's the case then I think the bug is in `wasmprinter` then:

```
$ cat foo.wat
(component
  (type (instance
    (type string)
    (export "" (type (eq 0)))
  ))
)
$ wasm-tools print foo.wat
(component
  (type (;0;)
    (instance
      (type (;0;) string)
      (export ""  (type 0))
    )
  )
)
```

**Comment by peterhuene** [comment]
I think that's the case.

Regarding type imports in the validator being rejected: it is bailing on them since at the time it wasn't quite clear how they were going to work as originally the type bounds weren't present in the spec.

Since only strict equality is supported in the spec, we could implement it as simply creating a new index in the type sort for the imported type (the utility of which escapes me).
