### ISSUE TITLE
documentation installation does not work

### ISSUE THREAD

**Issue by grishasobol** [bytecodealliance/wasm-tools#754]
When I try to do this
https://github.com/bytecodealliance/wasm-tools/blob/e71ba20d971f192fb1b8b3a0d6a10475871f38db/crates/wasm-smith/README.md?plain=1#L88-L95

then  this message is appear:
```bash
$ cargo install --git https://github.com/bytecodealliance/wasm-tools wasm-smith
    Updating git repository `https://github.com/bytecodealliance/wasm-tools`
error: there is nothing to install in `wasm-smith v0.11.4 (https://github.com/bytecodealliance/wasm-tools#e71ba20d)`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency in a Cargo project instead.
```

**Comment by alexcrichton** [comment]
Ah those instructions need to be updated, they should recommend `cargo install wasm-tools` and usage is `wasm-tools smith ...`. 

Would you be up for sending a PR to udpate the instructions?

**Comment by Lost-Temple** [comment]
when I excuted `cargo install wasm-tools`  , I got the error below: 

error[E0658]: use of unstable library feature 'array_from_fn'
   --> /Users/xxx/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/arbitrary-1.1.6/src/lib.rs:655:36
    |
655 |         crate::size_hint::and_all(&array::from_fn::<_, N, _>(|_| {
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information

error[E0747]: constant provided when a type was expected
   --> /Users/xxx/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/arbitrary-1.1.6/src/lib.rs:655:56
    |
655 |         crate::size_hint::and_all(&array::from_fn::<_, N, _>(|_| {
    |                                                        ^
    |
    = note: type arguments must be provided before constant arguments
    = help: reorder the arguments: types, then consts: `<F, T, N>`

Some errors have detailed explanations: E0658, E0747.
For more information about an error, try `rustc --explain E0658`.
error: could not compile `arbitrary` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-tools v1.0.10`, intermediate artifacts can be found at `/var/folders/c4/yxvm0t0d3p5fkhtdz0p0_rf80000gn/T/cargo-installkFAaZM`

Caused by:
  build failed

**Comment by peterhuene** [comment]
Hi @Lost-Temple. `array::from_fn` was stabilized in 1.63.0, release a few weeks back.

My guess is you need to update your Rust toolchain to the latest version to install `wasm-tools` with the latest dependencies or, alternatively, install with the `--locked` option to use force `cargo` to use the versions from the lock file.

**Comment by Lost-Temple** [comment]
thx, it worked.

1. rustup update stable --no-self-update && rustup default stable
2. cargo install wasm-tools

thank you very much
