### ISSUE TITLE
wasmprinter appears to produce invalid wat when labels are shadowed

### ISSUE THREAD

**Issue by nagisa** [bytecodealliance/wasm-tools#863]
It is possible to observe parse failures when parsing & printing some of the webassembly spec test suite test cases and feeding the printed result to the reference interpreter.

In particular tests like `if.wast` and `labels.wast` fail, because functions [like these](https://github.com/WebAssembly/spec/blob/937fc7d63efb9e18f36334a9e761a8a040ac44b7/test/core/labels.wast#L281-L288) become a

```wast
  (func (;19;) (type 0) (result i32)
    block $l1 (result i32) ;; label = @1
      block $#label1<l1> (@name "l1") (result i32) ;; label = @2
        i32.const 2
      end
      block $#label2<l1> (@name "l1") (result i32) ;; label = @2
        i32.const 3
        br 0 (;@2;)
      end
      i32.add
    end
  )

```

which the reference interpreter is unable to stomach due to `@name ...`. Is there a reason why these don’t just produce a `$l1` in the first place?

**Comment by alexcrichton** [comment]
The `@name` syntax appears even for same-named `func` annotations, so if it that causes the reference interpreter to choke here I suspect it would be unable to parse that syntax as well. Is the issue here though that the reference interpreter's text parser itself cannot parse this, or `wast` cannot parse this?

**Comment by nagisa** [comment]
I’m looking to feed the outputs of `wasm-printer` to the reference interpreter, but the more general expectation I had is that `wasm-printer` outputs valid `wat` as it is specified in the specification. Was such expectation misdirected? Either way, I don’t believe the text format specified in the spec references `@name` annotations in any shape or form.

(I could just discard the name section entirely, but the outputs here _also_ appear in the test snapshots, so keeping the section would be ideal for my use-case; as usual, I’m happy to look into fixing this…)

**Comment by alexcrichton** [comment]
This repository gets ahead of the reference interpreter in terms of proposals and specifically what you're seeing here is the [annotations proposal](https://github.com/WebAssembly/annotations). I've hoped that low-level crates like `wasmprinter` and `wast` wouldn't need to grow features based on proposals ideally, but that's one possible solution to this.

I think though that `wasmprinter` is probably at fault here, even in the fact of the annotations proposal. I think this test is specifically testing shadowing in which case this funky `$#label...` syntax isn't required since shadowing is what you get anyway. It's probably ok to remove the support from `wasmprinter` to print labels with `@name` optionally.

**Comment by nagisa** [comment]
I’d be happy enough with annotations still being enabled by default as long as they aren’t produced in the cases where labels are being simply shadowed. I’ll investigate and see what may make the most sense to implement. Ultimately having nice printing with shadowed names is going to be at least a nice-to-have in whatever future in which annotations proposal makes it to stable.

**Comment by alexcrichton** [comment]
To clarify the existence of `@name` printouts there is to be able to print something that the text format cannot natively express, which is a `name` section that has two functions with the same name. You can't naturally write that in the text format because two names with the same `$name` is a text parser error. With `@name`, however, they get unique `$name`s but still get the same `name` custom section as before.

The logic to implement all that for functions and other items was applied to labels as well, but labels are different than all other items where shadowing is allowed. In that sense the application of `@name` to same-named labels is a bug and one that should be fixed. I don't think `@name` should ever be used for labels given that shadowing is allowed.

**Comment by nagisa** [comment]
This I believe is resolved now.
