### ISSUE TITLE
Release soon?

### ISSUE THREAD

**Issue by bvisness** [bytecodealliance/wasm-tools#920]
Hey, I was just curious if we could do a release of wasm-tools soon. My work at Mozilla now depends on the `url` fix I recently submitted.

(If that's an issue, no worries, my work can wait.)

**Comment by alexcrichton** [comment]
Sure yeah. I'm hoping to land https://github.com/bytecodealliance/wasm-tools/pull/918 today and with that I'll publish new versions of crates.

**Comment by chenrui333** [comment]
@alexcrichton 👋 looks like the wasm-tools 1.0.23 release was not fully completed (i.e. the binaries for the tag did not get uploaded). Kind of relates to [the homebrew version bump](https://github.com/Homebrew/homebrew-core/pull/122906) as well. Thanks!!

**Comment by alexcrichton** [comment]
Ah I need to figure out a better way to remember this since github actions doesn't run CI when multiple tags are pushed and I typically push them all up at once. Thanks for the reminder, though, and [CI should complete in the near future](https://github.com/bytecodealliance/wasm-tools/actions/runs/4157905432) hopefully.

**Comment by chenrui333** [comment]
@alexcrichton looks like 1.0.28 release was not completed again (i.e. the release did not get marked as latest release 😅 )

relates to https://github.com/Homebrew/homebrew-core/pull/125335

**Comment by alexcrichton** [comment]
Sorry about that! Looks like the tag build didn't trigger, so I re-pushed the tag to kick CI into building release binaries.

**Comment by chenrui333** [comment]
Big thanks!! Gonna redo the homebrew PR now.
